### ISSUE TITLE
CID equivalence vs identity: how to implement `==`?

### ISSUE THREAD

**Issue by d70-t** [hashberg-io/multiformats#2] opened 2022-01-16 11:57 UTC
CIDs can be encoded in various formats, while referring to identical objects. This can lead to subtle problems regarding equality.

In particular, I expected the following code snippet to return `True`:

```python
In [1]: from multiformats import CID

In [2]: cid = CID("base32", 1, "raw", ("sha2-256", "2C26B46B68FFC68FF99B453C1D30413413422D706483BFA0F98A5E886266E7AE"))

In [3]: CID.decode(bytes(cid)) == cid
Out[3]: False
```

it returns `False`, because currently equality is based on the `tuple`-representation and `CID.decode` defaults to `'base58btc'` in stread of `'base32'`.

**Question:** Whouldn't it be better to implement equality based of the CID identifies the same thing in strad of if the CID looks the same?

---

While in the scenario above, it would be easy to add another method (like `.refers_to_same(other)` etc...) to explicitly check if the CID refers to the same thing, things get more complicated when combining CID with `dag-cbor` (continuing the code above):

```python
In [4]: import dag_cbor

In [5]: o = {"foo": cid}

In [6]: o2 = dag_cbor.decode(dag_cbor.encode(o))

In [7]: o2 == o
Out[7]: False
```

I really would like to have objects rounttripped through dag-cbor to compare equally.

As far as I understand, the `bytes`-representation of any CID is uniquely defined. If that's true, I'm suggesting to implement `__eq__` and `__hash__` based on `bytes`. I could also prepare a PR.

**Comment by sg495** [comment] 2022-01-16 17:20
You're absolutely right: CID equality should not depend on the choice of multibase (which is included merely for convenience of representation). It was a simple enough change, so I just committed b76a9ea5595f9e19da747c051eff5a344cfa608d to this effect. I just checked with dag-cbor v0.2.2 and it seems the problem is solved:

```py
>>> import dag_cbor
>>> from multiformats import CID
>>> cid = CID("base32", 1, "raw", ("sha2-256", "2C26B46B68FFC68FF99B453C1D30413413422D706483BFA0F98A5E886266E7AE"))
>>> CID.decode(bytes(cid)) == cid
True
>>> o = {"foo": cid}
>>> o2 = dag_cbor.decode(dag_cbor.encode(o))
>>> o2 == o
True
```

I you had something further in mind, a PR is always welcome 👍.

**Comment by d70-t** [comment] 2022-01-17 09:36
As far as I can see for now, this is a fine solution. Thanks 👍

**Closed** 2022-01-18 13:36 UTC

**Comment by sg495** [comment] 2022-01-18 13:37
BTW: I'll make a few extra tweaks today, then make a new micro release with this.

**Comment by d70-t** [comment] 2022-05-05 23:11
Hi @sg495, I just wanted to check back if there are chances for a new (micro) release in near time?
